### **(0) 환경 설정**

In [1]:
# ========================================
# 라이브러리 로드
# ========================================
from IPython.display import display
from pprint import pprint

import pandas as pd

In [2]:
# FnB 도메인에 속하는 기업 영상들 중 숏츠 영상 필터링
df_food = pd.read_csv("../../data/filtered_food_with_redirect.csv", encoding='utf-8')

# domain 컬럼 추가
df_food['domain'] = 'FnB'

print(df_food.shape)
print('-'*30)
pprint(df_food.info())
print('-'*30)
pprint(df_food['verdict'].value_counts())

(10852, 26)
------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 10852 entries, 0 to 10851
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  10852 non-null  int64
 1   video_id                    10852 non-null  str
 2   title                       10852 non-null  str
 3   channel_id                  10852 non-null  str
 4   channel_title               10852 non-null  str
 5   description                 10215 non-null  str
 6   upload_date                 10852 non-null  str
 7   tags                        4507 non-null   str
 8   category_id                 10852 non-null  int64
 9   view_count                  10852 non-null  int64
 10  like_count                  9990 non-null   float64
 11  comment_count               10691 non-null  float64
 12  duration                    10852 non-null  str
 13  definition                  10852 non-null  str
 14  license                     10852 non-null  str
 15  embeddable                  10852 non-null  bool
 16  has_paid_product_placement  10852 non-null  bool
 17  thumbnail                   10852 non-null  str
 18  thumbnail_h                 10852 non-null  int64
 19  thumbnail_w                 10852 non-null  int64
 20  caption                     10852 non-null  bool
 21  year                        10852 non-null  int64
 22  verdict                     10850 non-null  str
 23  reasoning                   10850 non-null  str
 24  final_url                   10850 non-null  str
 25  domain                      10852 non-null  str
dtypes: bool(3), float64(2), int64(6), str(15)
memory usage: 12.2 MB
None
------------------------------
verdict
shorts      5534
longform    5316
Name: count, dtype: int64

In [3]:
df_food_shorts = df_food[df_food['verdict'] == 'shorts']

print(len(df_food_shorts))

5534

In [4]:
# IT 도메인에 속하는 기업 영상들 중 숏츠 영상 필터링
df_it = pd.read_csv("../../data/filtered_it_with_redirect.csv", encoding='utf-8')

# domain 컬럼 추가
df_it['domain'] = 'IT'

print(df_it.shape)
print('-'*30)
pprint(df_it.info())
print('-'*30)
pprint(df_it['verdict'].value_counts())

(8431, 26)
------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 8431 entries, 0 to 8430
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  8431 non-null   int64
 1   video_id                    8431 non-null   str
 2   title                       8431 non-null   str
 3   channel_id                  8431 non-null   str
 4   channel_title               8431 non-null   str
 5   description                 7858 non-null   str
 6   upload_date                 8431 non-null   str
 7   tags                        5550 non-null   str
 8   category_id                 8431 non-null   int64
 9   view_count                  8431 non-null   int64
 10  like_count                  7281 non-null   float64
 11  comment_count               7231 non-null   float64
 12  duration                    8431 non-null   str
 13  definition                  8431 non-null   str
 14  license                     8431 non-null   str
 15  embeddable                  8431 non-null   bool
 16  has_paid_product_placement  8431 non-null   bool
 17  thumbnail                   8431 non-null   str
 18  thumbnail_h                 8431 non-null   int64
 19  thumbnail_w                 8431 non-null   int64
 20  caption                     8431 non-null   bool
 21  year                        8431 non-null   int64
 22  verdict                     8431 non-null   str
 23  reasoning                   8431 non-null   str
 24  final_url                   8431 non-null   str
 25  domain                      8431 non-null   str
dtypes: bool(3), float64(2), int64(6), str(15)
memory usage: 10.7 MB
None
------------------------------
verdict
longform    5958
shorts      2473
Name: count, dtype: int64

In [5]:
df_it_shorts = df_it[df_it['verdict'] == 'shorts']

print(len(df_it_shorts))

2473

---
#### 모델 성능 테스트용 데이터셋 제작
- IT 도메인 영상: 3개
- Food 도메인 영상: 3개

In [7]:
it_sample = df_it_shorts.iloc[426:428]
food_sample = df_food_shorts.iloc[428:430]

display(it_sample)
print("="*60)
display(food_sample)

,Unnamed: 0,video_id,title,channel_id,channel_title,description,upload_date,tags,category_id,view_count,...,has_paid_product_placement,thumbnail,thumbnail_h,thumbnail_w,caption,year,verdict,reasoning,final_url,domain
1197,1644,xGTnEUZiX3Q,"큰 TV에 딱 맞는 고화질, 참지말고 B tv IPTV로 바꾸자! (문의 1600-...",UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,아직도 IPTV로 안 바꾸셨어요?\n\nTV만 큰 TV로 바꾸면 뭐해요?\nUHD ...,2026-01-08 05:18:29+00:00,NaN,1,887889,...,False,https://i.ytimg.com/vi/xGTnEUZiX3Q/hqdefault.jpg,360,480,False,2026,shorts,kept /shorts route,https://www.youtube.com/shorts/xGTnEUZiX3Q,IT
1199,1646,QTnJv7w23kw,볼 게 더 풍성하니까 참지말고 B tv IPTV로 바꾸자! (문의 1600-2345),UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,아직도 IPTV로 안 바꾸셨어요?\n\n돌려도 돌려도 볼 게 없는 TV는 그만!\n...,2026-01-08 05:06:21+00:00,NaN,1,114613,...,False,https://i.ytimg.com/vi/QTnJv7w23kw/hqdefault.jpg,360,480,False,2026,shorts,kept /shorts route,https://www.youtube.com/shorts/QTnJv7w23kw,IT

============================================================

,Unnamed: 0,video_id,title,channel_id,channel_title,description,upload_date,tags,category_id,view_count,...,has_paid_product_placement,thumbnail,thumbnail_h,thumbnail_w,caption,year,verdict,reasoning,final_url,domain
659,659,-y1n3QG7y1I,🏀 : ??? 당황... 스럽다... | CU콘서트 #4강 #B조 #2라운드,UCsM07dUwo0WOWhFbVsG8K6A,CU [씨유튜브],스탠딩 코미디의 부활! [CU콘서트]\n\nCU 공채 개그맨에 한 걸음 더 다가선\...,2023-02-12 09:00:11+00:00,"CU편의점, CU, 씨유, 헤이루, Heyroo, cu콘서트, cuconcert, ...",24,70815,...,False,https://i.ytimg.com/vi/-y1n3QG7y1I/hqdefault.jpg,360,480,False,2023,shorts,kept /shorts route,https://www.youtube.com/shorts/-y1n3QG7y1I,FnB
660,660,iXnH_EhNmgk,편의점으로 따라와 이 친구야🔫 | CU콘서트 #4강 #B조 #1라운드,UCsM07dUwo0WOWhFbVsG8K6A,CU [씨유튜브],스탠딩 코미디의 부활! [CU콘서트]\n\nCU 공채 개그맨에 한 걸음 더 다가선\...,2023-02-11 09:00:42+00:00,"CU편의점, CU, 씨유, 헤이루, Heyroo, cu콘서트, cuconcert, ...",24,98820,...,False,https://i.ytimg.com/vi/iXnH_EhNmgk/hqdefault.jpg,360,480,False,2023,shorts,kept /shorts route,https://www.youtube.com/shorts/iXnH_EhNmgk,FnB

In [8]:
df_test = pd.concat([it_sample, food_sample], ignore_index=True)
df_test.to_csv("../Haeun/video_analysis/data/shorts-analysis_test-1-GCS활용테스트.csv", index=False, encoding='utf-8-sig')